### ISSUE TITLE
Error in running model b/c capitalization

### ISSUE THREAD

**Issue by kellijohnson** [kaskr/TMB_contrib_R#5]
`obj` is written as `Obj` which normally doesn't throw an error unless you do not name the optimization `Obj` in your global workspace.

https://github.com/kaskr/TMB_contrib_R/blob/b44fd1ad1fa717a78ef45dd2ae6eb346363f1dd4/TMBhelper/R/Optimize.R#L93

**Comment by James-Thorson** [comment]
please try it now

**Comment by kellijohnson** [comment]
Yes it appears to be working now. Thank you @James-Thorson.
