### ISSUE TITLE
sdreport not bound to a package

### ISSUE THREAD

**Issue by kellijohnson** [kaskr/TMB_contrib_R#7]
Can we bind the three calls to ```sdreport``` in ```Optimize``` to TMB, using ```TMB::sdreport```?

https://github.com/kaskr/TMB_contrib_R/blob/2071ec99dcb8df4dccd2866dea2528257c37bb4c/TMBhelper/R/Optimize.R#L94

**Comment by James-Thorson** [comment]
sure could you do a pull request.
